config/routes.rb
Rails.application.routes.draw do

  resources :foos
  resources :grupos
  resources :redes
  resources :equipes
  resources :sub_equipes

  resources :cargos

  resources :celulas do
    resource :celulas_membros, path: 'membros' do
      get 'search', on: :collection
    end
  end

  resources :hierarquia do
    get 'preencher_igrejas', on: :collection
    get 'preencher_cargos', on: :collection
    get 'preencher_responsaveis', on: :collection
    get 'preencher_redes', on: :collection
    get 'preencher_equipes', on: :collection
    get 'preencher_sub_equipes', on: :collection
    get 'preencher_celulas', on: :collection
  end

  resources :enderecos do
    post 'bairros', on: :collection
    post 'cidades', on: :collection
    post 'estados', on: :collection
    post 'paises', on: :collection

    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    get 'buscar_paises', on: :collection

    get 'bairro', on: :collection

  end

  resources :usuarios do
    get 'reset_password', on: :member
    post 'change_grupo', on: :member
    get 'ativar', on: :member
    get 'bloquear', on: :member
  end

  get 'users', to: 'usuarios#index'

  devise_for :users, controllers: {
                 confirmations: 'users/confirmations',
                 omniauth: 'users/omniauth',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 unlocks: 'users/unlocks'
                   }

  resources :igrejas do
    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    post 'add_contato', on: :collection
  end

  resources :membros do
    resources :contribuicoes do
      match 'report' => 'contribuicoes#report', via: [:get, :post], as: :report, on: :collection
    end
    collection do

      match 'search' => 'membros#search', via: [:get, :post], as: :search
      match 'report' => 'membros#report', via: [:get, :post], as: :report
    end
  end

  resources :tipo_contribuicoes

  scope module: :reports do
    resources :ultima_contribuicao, only: :index do
      collection do
        match 'report' => 'ultima_contribuicao#report', via: [:get, :post], as: :report
      end
    end

    resources :contribuicao_anual, only: :index do
      collection do
        match 'report' => 'contribuicao_anual#report', via: [:get, :post], as: :report
      end
    end

    resources :membros_contribuicoes, only: :index do
      collection do
        match 'report' => 'membros_contribuicoes#report', via: [:get, :post], as: :report
      end
    end

  end

  root 'dashboard#index'

end

app/models/cargo.rb
# == Schema Information
#
# Table name: cargos
#
#  id         :integer          not null, primary key
#  descricao  :string
#  lideranca  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cargo < ActiveRecord::Base

  validates :descricao, presence: true

  def lidera
    if lideranca
      'SIM'
    else
      'NAO'
    end
  end

end

app/controllers/cargos_controller.rb
# == Schema Information
#
# Table name: cargos
#
#  id         :integer          not null, primary key
#  descricao  :string
#  lideranca  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update]

  def index
    @tela = 'Listar Cargos'
    @cargos = Cargo.all
  end

  def show
    @tela = 'Visualizar Cargo'
  end

  def edit
    @tela = 'Editar Cargo'
  end

  def new
    @tela = 'Cadastrar Cargo'
    @cargo = Cargo.new(lideranca: false)
  end

  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Salvo com sucesso.' }
      else
        format.html { render :new }
      end
    end

  end

  def update

    respond_to do |format|

      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end

  end

  private

  def set_cargo
    @cargo = Cargo.find(params[:id])
  end

  def cargo_params
    params.require(:cargo).permit(:descricao, :lideranca )
  end
end

app/helpers/cargos_helper.rb
# == Schema Information
#
# Table name: cargos
#
#  id         :integer          not null, primary key
#  descricao  :string
#  lideranca  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_for @cargo, :html => {:class => "form-horizontal"} do |f| %>

    <%= render 'layouts/erros', object: @cargo %>

    <div class="form-group">
        <label class="col-lg-1 control-label">Descrição</label>
        <div class="col-lg-11">
            <%= f.text_field  :descricao, class: 'form-control', placeholder: 'Descrição'  %>
        </div>
    </div>

    <div class="form-group">
      <label class="col-lg-1 control-label">Liderança</label>
      <div class="col-lg-11">
        <div class="radio">
          <label>
            <%= f.radio_button :lideranca, true %>
            <span class="text">SIM</span>
          </label>
        </div>
        <div class="radio">
          <label>
            <%= f.radio_button :lideranca, false %>
            <span class="text">NAO</span>
          </label>
        </div>


      </div>
    </div>

    <%= link_to 'Listar', cargos_path, class: 'btn btn-blue' %>

    <%= f.submit class: 'btn btn-blue' %>

<% end %>

app/views/cargos/index.html.erb
<%= bootstrap_form_tag url: '/filtrar' do |f| %>

    <div class="form-group">
      <div class="col-sm-12 text-right" style="padding-bottom: 5px">
        <%= link_to new_cargo_path, title: 'Novo', class: 'btn btn-success btn-circle btn-xs' do %>
            <%= fa_icon 'plus' %>
        <% end %>
      </div>
      <div class="col-sm-12">
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>#</th>
            <th>Descrição </th>
            <th>Liderança</th>
            <th width="20"></th>
            <th width="20"></th>

          </tr>
          </thead>

          <tbody>
          <% @cargos.each do |cargo| %>
              <tr>
                <td><%= cargo.id %></td>
                <td><%= cargo.descricao %></td>
                <td><%= cargo.lidera %></td>
                <td>
                  <%= link_to cargo, title: 'Visualizar', class: 'btn btn-default btn-xs icon-only ' do %>
                      <%= fa_icon 'search' %>
                  <% end %>
                </td>
                <td>
                  <%= link_to edit_cargo_path(cargo), title: 'Editar', class: 'btn btn-default btn-xs icon-only ' do %>
                      <%= fa_icon 'pencil' %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

<% end %>

app/views/cargos/show.html.erb
<form action="" class="form-horizontal">

  <div class="form-title">
    Informações
  </div>

  <div class="form-group">
    <label class="col-lg-1 control-label">Descrição</label>
    <div class="col-lg-11">
      <input type="text" class='form-control' disabled value="<%=	 @cargo.descricao  %>">
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-1 control-label">Lideranca</label>
    <div class="col-lg-11">
      <input type="text" class='form-control' disabled value="<%=	 @cargo.lidera  %>">
    </div>
  </div>

  <%= link_to 'Listar', cargos_path, class: 'btn btn-blue' %>
  <%= link_to 'Editar', edit_cargo_path(@cargo), class: 'btn btn-blue' %>

</form>