config/routes.rb
Rails.application.routes.draw do

  resources :foos
  resources :grupos
  resources :redes
  resources :equipes
  resources :sub_equipes

  resources :cargos

  resources :celulas do
    resource :celulas_membros, path: 'membros' do
      get 'search', on: :collection
    end
  end

  resources :hierarquia do
    get 'preencher_igrejas', on: :collection
    get 'preencher_cargos', on: :collection
    get 'preencher_responsaveis', on: :collection
    get 'preencher_redes', on: :collection
    get 'preencher_equipes', on: :collection
    get 'preencher_sub_equipes', on: :collection
    get 'preencher_celulas', on: :collection
  end

  resources :enderecos do
    post 'bairros', on: :collection
    post 'cidades', on: :collection
    post 'estados', on: :collection
    post 'paises', on: :collection

    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    get 'buscar_paises', on: :collection

    get 'bairro', on: :collection

  end

  resources :usuarios do
    get 'reset_password', on: :member
    post 'change_grupo', on: :member
    get 'ativar', on: :member
    get 'bloquear', on: :member
  end

  get 'users', to: 'usuarios#index'

  devise_for :users, controllers: {
                 confirmations: 'users/confirmations',
                 omniauth: 'users/omniauth',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 unlocks: 'users/unlocks'
                   }

  resources :igrejas do
    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    post 'add_contato', on: :collection
  end

  resources :membros do
    resources :contribuicoes do
      match 'report' => 'contribuicoes#report', via: [:get, :post], as: :report, on: :collection
    end
    collection do

      match 'search' => 'membros#search', via: [:get, :post], as: :search
      match 'report' => 'membros#report', via: [:get, :post], as: :report
    end
  end

  resources :tipo_contribuicoes

  scope module: :reports do
    resources :ultima_contribuicao, only: :index do
      collection do
        match 'report' => 'ultima_contribuicao#report', via: [:get, :post], as: :report
      end
    end

    resources :contribuicao_anual, only: :index do
      collection do
        match 'report' => 'contribuicao_anual#report', via: [:get, :post], as: :report
      end
    end

    resources :membros_contribuicoes, only: :index do
      collection do
        match 'report' => 'membros_contribuicoes#report', via: [:get, :post], as: :report
      end
    end

  end

  root 'dashboard#index'

end

app/models/rede.rb
# == Schema Information
#
# Table name: redes
#
#  id             :integer          not null, primary key
#  descricao      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  responsavel_id :integer
#  igreja_id      :integer
#

class Rede < ActiveRecord::Base

  belongs_to :responsavel, class_name: "Membro", foreign_key: "responsavel_id"
  belongs_to :igreja

  validates :descricao, presence:true
  validates :responsavel_id, presence:true


  def to_s
    descricao
  end
end

app/controllers/redes_controller.rb
# == Schema Information
#
# Table name: redes
#
#  id             :integer          not null, primary key
#  descricao      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  responsavel_id :integer
#  igreja_id      :integer
#

class RedesController < ApplicationController

  before_action :set_rede, only: [:show, :edit, :update]

  def index
    @tela = 'Listar Redes'
    @redes = Rede.none

    if current_user.tem_permissao ['usuarioPodeAcessarTodosOsNiveisDaIgreja']
      @redes = Rede.where(igreja_id: current_user.igrejas_ids).order(:descricao)
    else
      membro = Membro.find_by_user_id(current_user.id)

      unless membro.nil?
        @redes = Rede.where(id: membro.redes_ids).order(:descricao)
      else
        @redes = Rede.none
      end
    end

    authorize @redes
  end

  def show
    @tela = 'Visualizar Rede'
  end

  def edit
    @tela = 'Editar Rede'
  end

  def new
    @tela = 'Cadastrar Rede'
    @rede = Rede.new
  end

  def create
    @rede = Rede.new(rede_params)

    respond_to do |format|
      if @rede.save
        format.html { redirect_to @rede, notice: 'Salvo com sucesso.' }
      else
        format.html { render :new }
      end
    end

  end

  def update

    respond_to do |format|
      if @rede.update(rede_params)
        format.html { redirect_to @rede, notice: 'Atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end

  end

  private

  def set_rede
    @rede = Rede.find(params[:id])
  end

  def rede_params
    params.require(:rede).permit(:descricao, :responsavel_id, :igreja_id)
  end

end

app/helpers/redes_helper.rb
# == Schema Information
#
# Table name: redes
#
#  id             :integer          not null, primary key
#  descricao      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  responsavel_id :integer
#  igreja_id      :integer
#

module RedesHelper
end

app/views/redes/_form.html.erb
<%= bootstrap_form_for(@rede,layout: :horizontal, label_col: 'col-sm-1', control_col: 'col-sm-11') do |f| %>

    <%= hidden_field_tag :arquivo, 'new-edit-form' %>

    <%= hidden_field_tag :id_responsavel, unless @rede.responsavel.nil? then @rede.responsavel.id else 0 end %>
    <%= hidden_field_tag :id_igreja, unless @rede.igreja.nil? then @rede.igreja.id else 0 end %>

    <div class="form-group">

      <div class="col-sm-6">
        <%= f.select :igreja_id, [], {label_col:'col-sm-2', control_col: 'col-sm-10', label_class: 'no-padding-right'} %>
      </div>

      <div class="col-sm-6">
        <%= f.select :responsavel_id, [], {label_col:'col-sm-2', control_col: 'col-sm-10', label_class: 'no-padding-right'} %>
      </div>

      <div class="col-sm-12">
        <%= f.text_field :descricao, label: 'Descrição', placeholder: 'Descrição', label_class: 'no-padding-right'  %>
      </div>

    </div>

    <%= link_to 'Listar', redes_path, class: 'btn btn-blue' %>

    <%= f.submit class: 'btn btn-blue' %>

<% end %>

app/views/redes/index.html.erb
<%= bootstrap_form_tag url: '/filtrar' do |f| %>

    <div class="form-group">
      <div class="col-sm-12 text-right" style="padding-bottom: 5px">
        <%= link_to new_rede_path, title: 'Novo', class: 'btn btn-success btn-circle btn-xs' do %>
            <%= fa_icon 'plus' %>
        <% end %>
      </div>
      <div class="col-sm-12">
        <table class="table table-hover table-bordered">
          <thead>
          <tr>

            <th>Descrição </th>
            <th>Igreja </th>
            <th>Responsável </th>
            <th width="20"></th>
            <th width="20"></th>

          </tr>
          </thead>

          <tbody>
          <% @redes.each do |rede| %>
              <tr>
                
                <td><%= rede.descricao %></td>
                <td><%= rede.igreja.descricao %></td>
                <td><%= rede.responsavel.pessoa.nome unless rede.responsavel.nil? %></td>
                <td>
                  <%= link_to rede, title: 'Visualizar', class: 'btn btn-default btn-xs icon-only' do %>
                      <%= fa_icon 'search' %>
                  <% end %>
                </td>
                <td>
                  <%= link_to edit_rede_path(rede), title: 'Editar', class: 'btn btn-default btn-xs icon-only' do %>
                      <%= fa_icon 'pencil' %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

<% end %>

app/views/redes/show.html.erb
<form action="" class="form-horizontal">

  <div class="form-group">
    <%= label_tag :igreja, nil, class: 'col-md-1 control-label no-padding-right' %>
    <div class="col-md-5">
      <%= text_field_tag :igreja, @rede.igreja.descricao, class: 'form-control', disabled: 'disabled' %>
    </div>

    <%= label_tag :responsavel, 'Responsável', class: 'col-md-1 control-label no-padding-right' %>
    <div class="col-md-5">
      <%= text_field_tag :responsavel, @rede.responsavel.pessoa.nome, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :descricao, 'Descrição', class: 'col-md-1 control-label no-padding-right' %>
    <div class="col-md-11">
      <%= text_field_tag :descricao, @rede.descricao, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>

  <%= link_to 'Listar', redes_path, class: 'btn btn-blue' %>
  <%= link_to 'Editar', edit_rede_path(@rede), class: 'btn btn-blue' %>

</form>