config/routes.rb
Rails.application.routes.draw do

  resources :foos
  resources :grupos
  resources :redes
  resources :equipes
  resources :sub_equipes

  resources :cargos

  resources :celulas do
    resource :celulas_membros, path: 'membros' do
      get 'search', on: :collection
    end
  end

  resources :hierarquia do
    get 'preencher_igrejas', on: :collection
    get 'preencher_cargos', on: :collection
    get 'preencher_responsaveis', on: :collection
    get 'preencher_redes', on: :collection
    get 'preencher_equipes', on: :collection
    get 'preencher_sub_equipes', on: :collection
    get 'preencher_celulas', on: :collection
  end

  resources :enderecos do
    post 'bairros', on: :collection
    post 'cidades', on: :collection
    post 'estados', on: :collection
    post 'paises', on: :collection

    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    get 'buscar_paises', on: :collection

    get 'bairro', on: :collection

  end

  resources :usuarios do
    get 'reset_password', on: :member
    post 'change_grupo', on: :member
    get 'ativar', on: :member
    get 'bloquear', on: :member
  end

  get 'users', to: 'usuarios#index'

  devise_for :users, controllers: {
                 confirmations: 'users/confirmations',
                 omniauth: 'users/omniauth',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 unlocks: 'users/unlocks'
                   }

  resources :igrejas do
    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    post 'add_contato', on: :collection
  end

  resources :membros do
    resources :contribuicoes do
      match 'report' => 'contribuicoes#report', via: [:get, :post], as: :report, on: :collection
    end
    collection do

      match 'search' => 'membros#search', via: [:get, :post], as: :search
      match 'report' => 'membros#report', via: [:get, :post], as: :report
    end
  end

  resources :tipo_contribuicoes

  scope module: :reports do
    resources :ultima_contribuicao, only: :index do
      collection do
        match 'report' => 'ultima_contribuicao#report', via: [:get, :post], as: :report
      end
    end

    resources :contribuicao_anual, only: :index do
      collection do
        match 'report' => 'contribuicao_anual#report', via: [:get, :post], as: :report
      end
    end

    resources :membros_contribuicoes, only: :index do
      collection do
        match 'report' => 'membros_contribuicoes#report', via: [:get, :post], as: :report
      end
    end

  end

  root 'dashboard#index'

end

app/models/foo.rb
# == Schema Information
#
# Table name: foos
#
#  id          :integer          not null, primary key
#  description :string
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Foo < ActiveRecord::Base
  validates :description, presence: true
end

app/controllers/foos_controller.rb
# == Schema Information
#
# Table name: foos
#
#  id          :integer          not null, primary key
#  description :string
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class FoosController < ApplicationController
  before_action :set_foo, only: [:show, :edit, :update, :destroy]

  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1
  # PATCH/PUT /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo.destroy
    respond_to do |format|
      format.html { redirect_to foos_url, notice: 'Foo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foo_params
      params.require(:foo).permit(:description, :number)
    end
end

app/helpers/foos_helper.rb
# == Schema Information
#
# Table name: foos
#
#  id          :integer          not null, primary key
#  description :string
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_for(@foo) do |f| %>
  <% if @foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% @foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form' %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foos</h1>

  <table class="table table-hover table-bordered">

  <thead>
    <tr>
      <th>Description</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= foo.description %></td>
        <td><%= foo.number %></td>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form' %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @foo.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @foo.number %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>