config/routes.rb
Rails.application.routes.draw do

  resources :foos
  resources :grupos
  resources :redes
  resources :equipes
  resources :sub_equipes

  resources :cargos

  resources :celulas do
    resource :celulas_membros, path: 'membros' do
      get 'search', on: :collection
    end
  end

  resources :hierarquia do
    get 'preencher_igrejas', on: :collection
    get 'preencher_cargos', on: :collection
    get 'preencher_responsaveis', on: :collection
    get 'preencher_redes', on: :collection
    get 'preencher_equipes', on: :collection
    get 'preencher_sub_equipes', on: :collection
    get 'preencher_celulas', on: :collection
  end

  resources :enderecos do
    post 'bairros', on: :collection
    post 'cidades', on: :collection
    post 'estados', on: :collection
    post 'paises', on: :collection

    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    get 'buscar_paises', on: :collection

    get 'bairro', on: :collection

  end

  resources :usuarios do
    get 'reset_password', on: :member
    post 'change_grupo', on: :member
    get 'ativar', on: :member
    get 'bloquear', on: :member
  end

  get 'users', to: 'usuarios#index'

  devise_for :users, controllers: {
                 confirmations: 'users/confirmations',
                 omniauth: 'users/omniauth',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 unlocks: 'users/unlocks'
                   }

  resources :igrejas do
    get 'buscar_cidades', on: :collection
    get 'buscar_estados', on: :collection
    get 'buscar_bairros', on: :collection
    post 'add_contato', on: :collection
  end

  resources :membros do
    resources :contribuicoes do
      match 'report' => 'contribuicoes#report', via: [:get, :post], as: :report, on: :collection
    end
    collection do

      match 'search' => 'membros#search', via: [:get, :post], as: :search
      match 'report' => 'membros#report', via: [:get, :post], as: :report
    end
  end

  resources :tipo_contribuicoes

  scope module: :reports do
    resources :ultima_contribuicao, only: :index do
      collection do
        match 'report' => 'ultima_contribuicao#report', via: [:get, :post], as: :report
      end
    end

    resources :contribuicao_anual, only: :index do
      collection do
        match 'report' => 'contribuicao_anual#report', via: [:get, :post], as: :report
      end
    end

    resources :membros_contribuicoes, only: :index do
      collection do
        match 'report' => 'membros_contribuicoes#report', via: [:get, :post], as: :report
      end
    end

  end

  root 'dashboard#index'

end

app/controllers/contribuicoes_controller.rb
# == Schema Information
#
# Table name: contribuicoes
#
#  id                   :integer          not null, primary key
#  valor                :decimal(10, 2)
#  tipo_contribuicao_id :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  membro_id            :integer
#  data                 :date
#

class ContribuicoesController < ApplicationController

  before_action :set_contribuicao, only: [:show, :edit, :update]
  before_action :preencher_listas, only: [:new, :edit]

  def index
    @membro = Membro.find(params[:membro_id])

    @contribuicoes = Contribuicao.where(membro_id: params[:membro_id]).reverse_order
  end

  def show

  end

  def edit


  end

  def new
    @membro = Membro.find(params[:membro_id])
    @contribuicao = @membro.contribuicaos.build
    @contribuicao.data = Time.new.to_date
  end

  def create
    @membro = Membro.find(params[:membro_id])
    @contribuicao = @membro.contribuicaos.create(contribuicao_params)

    respond_to do |format|
      if @contribuicao.save
        format.html { redirect_to membro_contribuicoes_path(@membro), notice: 'Salvo com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|

      if @contribuicao.update(contribuicao_params)
        format.html { redirect_to membro_contribuicoes_path(@contribuicao.membro), notice: 'Contribuição alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @contribuicao }
      else
        format.html { render :edit }
        format.json { render json: @contribuicao.errors, status: :unprocessable_entity }
      end
    end
  end

  def report
    index
    respond_to do |format|
      format.pdf do
        pdf = ContribuicaoMembroReport.new(@contribuicoes)

        send_data pdf.render, filename: "membros_contribuicoes_report.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  private

  def preencher_listas
    @tipo_ops = TipoContribuicao.all.collect.map do |t|
      [t.descricao, t.id]
    end
  end

  def set_contribuicao
    @contribuicao = Contribuicao.find(params[:id])
    @membro = @contribuicao.membro
  end

  def contribuicao_params
    params.require(:contribuicao).permit(:tipo_contribuicao_id, :valor, :data)
  end

end

app/helpers/contribuicoes_helper.rb
# == Schema Information
#
# Table name: contribuicoes
#
#  id                   :integer          not null, primary key
#  valor                :decimal(10, 2)
#  tipo_contribuicao_id :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  membro_id            :integer
#  data                 :date
#

module ContribuicoesHelper
end

app/views/contribuicoes/_form.html.erb
<%= form_for [@membro, @contribuicao] do |f| %>



    <%= render 'layouts/erros', object: @contribuicao %>


    <div class="form-group">
      <%= f.label :data, 'Data', class: 'col-md-1 control-label no-padding-right' %>
      <div class="col-md-3">
            <%= f.text_field :data, value: (@contribuicao.data.to_s(:br) unless @contribuicao.data.nil?), type: 'text', class: 'form-control date-picker', data:{date_format: 'dd/mm/yyyy'} %>
      </div>

      <%= f.label :tipo_contribuicao_id, 'Tipo', class: 'col-md-1 control-label no-padding-right' %>
      <div class="col-md-3">
        <%= f.select(:tipo_contribuicao_id, @tipo_ops, {}, {class: 'form-control'}) %>
      </div>

      <%= f.label :valor, class: 'col-md-1 control-label no-padding-right' %>

      <div class="col-md-3">
        <%= f.text_field :valor, type: 'text', class: 'form-control formatarMoeda', :value => number_to_currency(f.object.valor)%>
      </div>
    </div>

    <br>

    <div class="form-group" align="center">
      <button type="submit" class="btn btn-default">Confirmar</button>
    </div>

<% end %>

app/views/contribuicoes/edit.html.erb
<%= render 'form' %>

app/views/contribuicoes/index.html.erb
<%= bootstrap_form_tag url: '/filtrar' do |f| %>

    <div class="form-group">
      <div class="col-sm-12 text-right" style="padding-bottom: 5px">
        <%= link_to membros_path, title: 'Listar Membros', class: 'btn btn-success btn-circle btn-xs' do %>
            <%= fa_icon 'arrow-left' %>
        <% end %>
        <%= link_to new_membro_contribuicao_path(@membro), title: 'Novo', class: 'btn btn-success btn-circle btn-xs' do %>
            <%= fa_icon 'plus' %>
        <% end %>

        <%= link_to '#', title: 'Imprimir', class: 'btn btn-success btn-circle btn-xs btn-report', data: {action: report_membro_contribuicoes_path(format: 'pdf')} do %>
            <%= fa_icon 'print' %>
        <% end %>

      </div>
      <div class="col-sm-12">
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th width="20"></th>
          </tr>
          </thead>
          <tbody>
          <% @contribuicoes.each do |c| %>
              <tr>
                <td><%= c.data.to_s(:br) unless c.data.nil? %></td>
                <td><%= c.tipo_contribuicao.descricao %></td>
                <td><%= number_to_currency(c.valor) %></td>
                <td>
                  <%= link_to edit_membro_contribuicao_path(c.membro, c), title: 'Alterar', class: 'btn btn-default btn-xs icon-only' do %>
                      <%= fa_icon 'pencil' %>
                  <% end %>
                </td>

              </tr>
          <%end%>
          </tbody>
        </table>
      </div>
    </div>

<% end %>

app/views/contribuicoes/show.html.erb
<div class="form-group">
  <%= label_tag :descricao, 'Descrição', class: 'col-md-1 control-label no-padding-right' %>
  <div class="col-md-11">
    <%= text_field_tag :descricao, @tipo_contribuicao.descricao, class: 'form-control', disabled: 'disabled' %>
  </div>
</div>